pdf('../image/NormalS1.pdf', width = 15, height = 7)
par(mfcol  = c(2, 5))
plot(mod1)
plot(mod3)
plot(mod5)
plot(mod7)
plot(mod9)
dev.off()

pdf('../image/NormalS2.pdf', width = 15, height = 7)
par(mfcol  = c(2, 5))
plot(mod1)
plot(mod3)
plot(mod5)
plot(mod7)
plot(mod9)
dev.off()

pdf('../image/NormalS3.pdf', width = 15, height = 7)
par(mfcol  = c(2, 5))
plot(mod1)
plot(mod3)
plot(mod5)
plot(mod7)
plot(mod9)
dev.off()

pdf('../image/T3S1.pdf', width = 15, height = 7)
par(mfcol  = c(2, 5))
plot(mod1)
plot(mod3)
plot(mod5)
plot(mod7)
plot(mod9)
dev.off()

pdf('../image/T3S2.pdf', width = 15, height = 7)
par(mfcol  = c(2, 5))
plot(mod1)
plot(mod3)
plot(mod5)
plot(mod7)
plot(mod9)
dev.off()

pdf('../image/T3S3.pdf', width = 15, height = 7)
par(mfcol  = c(2, 5))
plot(mod1)
plot(mod3)
plot(mod5)
plot(mod7)
plot(mod9)
dev.off()

pdf('../image/LPS1.pdf', width = 15, height = 7)
par(mfcol  = c(2, 5))
plot(mod1)
plot(mod3)
plot(mod5)
plot(mod7)
plot(mod9)
dev.off()

pdf('../image/LPS2.pdf', width = 15, height = 7)
par(mfcol  = c(2, 5))
plot(mod1)
plot(mod3)
plot(mod5)
plot(mod7)
plot(mod9)
dev.off()

pdf('../image/LPS3.pdf', width = 15, height = 7)
par(mfcol  = c(2, 5))
plot(mod1)
plot(mod3)
plot(mod5)
plot(mod7)
plot(mod9)
dev.off()

pdf('../image/ToursGoF.pdf', width = 15, height = 7)
par(mfcol  = c(2, 5))
plot(mod1)
plot(mod3)
plot(mod5)
plot(mod7)
plot(mod9)
dev.off()

pdf('../image/ToursMNARGoF.pdf', width = 15, height = 7)
par(mfcol  = c(2, 5))
plot(mod1)
plot(mod3)
plot(mod5)
plot(mod7)
plot(mod9)
dev.off()
